source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.3'

target 'UIViewController-KeyboardAdditions' do
  pod "UIViewController-KeyboardAdditions", :path => "../"
end

target 'Tests' do
  pod "UIViewController-KeyboardAdditions", :path => "../"
end
