source 'https://github.com/CocoaPods/Specs.git'

target 'UIViewController-KeyboardAdditions', :exclusive => true do
  pod "UIViewController-KeyboardAdditions", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "UIViewController-KeyboardAdditions", :path => "../"

  
end
