# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage


osx_image: xcode12
language: objective-c
script:
- set -o pipefail && xcodebuild test -workspace Example/UIViewController-KeyboardAdditions.xcworkspace -scheme UIViewController-KeyboardAdditions-Example -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 11' ONLY_ACTIVE_ARCH=NO | xcpretty -c
- pod lib lint --quick
